apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: gontador-template
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes the gontador grpc service
    labels:
      app: gontador
    name: gontador-grpc
    namespace: gontador
  spec:
    ports:
      - name: gontador-grpc
        port: 3001
        nodePort: 30001
    selector:
      app: gontador
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes the gontador service
    labels:
      app: gontador
    name: gontador-http
    namespace: gontador
  spec:
    ports:
      - name: gontador-http
        port: 3000
        protocol: TCP
        targetPort: 3000
      # - name: gontador-grpc
      #   port: 3001
      #   protocol: TCP
      #   targetPort: 3001
    selector:
      app: gontador
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}

- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: gontador
    namespace: gontador
  spec:
    lookupPolicy:
      local: false


- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: gontador
    name: gontador
    namespace: gontador
  spec:
    replicas: 2
    selector:
      app: gontador
      deploymentconfig: gontador
    # strategy:
    #   activeDeadlineSeconds: 21600
    #   resources: {}
    #   rollingParams:
    #     intervalSeconds: 1d
    #     maxSurge: 25%
    #     maxUnavailable: 25%
    #     timeoutSeconds: 600
    #     updatePeriodSeconds: 1
    #   type: Rolling
    template:
      metadata:
        labels:
          app: gontador
          deploymentconfig: gontador
      spec:
        containers:
          - image: >-
              172.30.1.1:5000/gontador/gontador@sha256:9fd64c947842884d6def85ca5ee907efefb2c636960ca5069a06eb89adeda1ec
            imagePullPolicy: Always
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /health/live
                port: 3000
                scheme: HTTP
              initialDelaySeconds: 2
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 10
            name: gontador
            ports:
              - containerPort: 3000
                protocol: TCP
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /health/ready
                port: 3000
                scheme: HTTP
              initialDelaySeconds: 2
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 10
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            env:
              - name: SYSTEM_ENV
                value: dev
              - name: SYSTEM_INSTANCE
                value: demo-stao
              - name: SERVICE_HOST
                valueFrom:
                  fieldRef:
                    # apiVersion: v1
                    fieldPath: spec.nodeName
              - name: SERVICE_PORT
                value: '3000'
              - name: SERVICE_INSTANCE
                valueFrom:
                  fieldRef:
                    # apiVersion: v1
                    fieldPath: metadata.name
              - name: METRIC_HOST
                value: 192.168.1.2
              - name: METRIC_PORT
                value: '2003'
              - name: REDIS_URL
                value: '192.168.1.2:6379'
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
      - imageChangeParams:
          automatic: true
          containerNames:
            - gontador
          from:
            kind: ImageStreamTag
            name: 'gontador:latest'
            namespace: gontador
          lastTriggeredImage: >-
            172.30.1.1:5000/gontador/gontador@sha256:9fd64c947842884d6def85ca5ee907efefb2c636960ca5069a06eb89adeda1ec
        type: ImageChange
      - type: ConfigChange
  status: {}
